#
# Example of configuration for crawling all pages of the web sites in the seeds
#
target_storage.data_format.type: FILESYSTEM_JSON
target_storage.data_format.filesystem.compress_data: true
target_storage.english_language_detection_enabled: false

link_storage.max_pages_per_domain: 1000000000
link_storage.link_strategy.use_scope: true
link_storage.link_strategy.outlinks: true
link_storage.link_selector: MaximizeWebsitesLinkSelector
link_storage.download_sitemap_xml: true
link_storage.scheduler.host_min_access_interval: 2000
link_storage.scheduler.max_links: 1000

crawler_manager.downloader.user_agent.name: ACHE
crawler_manager.downloader.user_agent.url: https://github.com/ViDA-NYU/ache
